CREATE SCHEMA IF NOT EXISTS "public";
DROP TABLE IF EXISTS "public".matches;
CREATE TABLE "public".matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(255),
   match_date date NOT NULL,
   match_time TIME WITHOUT TIME ZONE NOT NULL,
   team_a VARCHAR(255) NOT NULL,
   team_b VARCHAR(255) NOT NULL,
   sport INTEGER NOT NULL,
   CONSTRAINT pk_match PRIMARY KEY (id)
);

ALTER TABLE "public".matches ADD CONSTRAINT uc_1213803dd8c00ebdef12559d6 UNIQUE (team_a, team_b, sport, match_date);

DROP TABLE IF EXISTS "public".match_odds;

CREATE TABLE "public".match_odds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   match_id BIGINT NOT NULL,
   specifier VARCHAR(255) NOT NULL,
   odd DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_match_odd PRIMARY KEY (id)
);

ALTER TABLE "public".match_odds ADD CONSTRAINT FK_MATCH_ODD_ON_MATCHID FOREIGN KEY (match_id) REFERENCES "public".matches (id);

